In [11]:
import numpy as np

In [9]:
def f(x):
    return np.sin(x / 5) * np.exp(x / 10) + 5 * np.exp(- x / 2)

In [49]:
x_1 = np.array([[1 ** 0, 1 ** 1], [15 ** 0, 15 ** 1]])
x_2 = np.array([[1 ** 0, 1 ** 1, 1 ** 2], [8 ** 0, 8 ** 1, 8 ** 2], [15 ** 0, 15 ** 1, 15 ** 2]])
x_3 = np.array([[1 ** 0, 1 ** 1, 1 ** 2, 1 ** 3], [4 ** 0, 4 ** 1, 4 ** 2, 4 ** 3],
                [10 ** 0, 10 ** 1, 10 ** 2, 10 ** 3], [15 ** 0, 15 ** 1, 15 ** 2, 15 ** 3]])

In [53]:
y_1 = np.array([f(1), f(15)])
y_2 = np.array([f(1), f(8), f(15)])
y_3 = np.array([f(1), f(4), f(10), f(15)])

In [58]:
w_1 = np.linalg.solve(x_1, y_1)
w_2 = np.linalg.solve(x_2, y_2)
w_3 = np.linalg.solve(x_3, y_3)

In [59]:
w_1

array([ 3.43914511, -0.18692825])

In [61]:
w_2

array([ 3.32512949, -0.06531159, -0.00760104])

In [62]:
w_3

array([ 4.36264154, -1.29552587,  0.19333685, -0.00823565])